"""remove slug to coffee table

Revision ID: 8351f0691c1c
Revises: 8244d92b5ab9
Create Date: 2024-08-04 00:00:49.620537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8351f0691c1c'
down_revision = '8244d92b5ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.drop_constraint('slug', type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(), nullable=False))
        batch_op.create_unique_constraint('slug', ['slug'])

    # ### end Alembic commands ###
