"""empty message

Revision ID: ac7ba14c19ed
Revises: 
Create Date: 2024-08-03 15:23:49.098947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7ba14c19ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('quiet', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('credit_card', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('food', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('wifi_rating', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('coffee_rating', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('power_rating', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=False))
        batch_op.alter_column('wifi',
               existing_type=sa.FLOAT(),
               type_=sa.Boolean(),
               existing_nullable=False)
        batch_op.alter_column('power',
               existing_type=sa.FLOAT(),
               type_=sa.Boolean(),
               existing_nullable=False)
        batch_op.alter_column('coffee',
               existing_type=sa.FLOAT(),
               type_=sa.Boolean(),
               existing_nullable=False)
        batch_op.alter_column('open',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('close',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_column('location')
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=250), nullable=False))
        batch_op.alter_column('close',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
        batch_op.alter_column('open',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
        batch_op.alter_column('coffee',
               existing_type=sa.Boolean(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('power',
               existing_type=sa.Boolean(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('wifi',
               existing_type=sa.Boolean(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('image_url')
        batch_op.drop_column('power_rating')
        batch_op.drop_column('coffee_rating')
        batch_op.drop_column('wifi_rating')
        batch_op.drop_column('food')
        batch_op.drop_column('credit_card')
        batch_op.drop_column('quiet')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
